### PR TITLE
Change time.clock() by time.time() due it function is depecated since…

### PR DESCRIPTION
**Pull request by Hierosme**
… version python 3.3, and will be removed in version 3.8,

Normaly can be replca by process_time() but time.time() to the job.

It have no test need that because nothing change, except a warning remove.

### CODE REVIEW

**Comment by Harmon758** [comment]
Duplicate of #6

**Comment by paulovn** [comment]
Thanks for the patch. There was already a PR containing the same fix. I've merged it, and generated version 0.9.3 (also uploaded to PyPi)

**Comment by Hierosme** [comment]
Please could you publish a new Pypi version with it fixe ?

Actually that is impossible to use pip install python-aiml

Then the actual version publish by pypi do not work well...

Regards

**Comment by paulovn** [comment]
Version 0.9.3 (the latest version, which has the latest code from `master`) **was** published on PyPi a couple of years ago: https://pypi.org/project/python-aiml/#history

I no longer do any work on this code, but I've just checked and I can `pip install python-aiml` without problems in a Python 3.8 environment. The installed program appears to work, at least superficially. Might it be a problem with another version of Python?

**Comment by Hierosme** [comment]
i redo tests and back to you. May be that me...

You work is the true aiml python reference, be sure of that ...

Regards

**Pull request closed without merging**
